### ISSUE TITLE
Information - new project to build PHP command-line tools

### ISSUE THREAD

**Issue by DavidAnderson684** [ecoofficekbo/hmrcmtd#1]
Hi James,

I don't know about you, but the idea of having to obtain Windows and commercial software to submit a VAT return that currently is free isn't a very welcome one. So, I was looking at the HMRC API, and then searching to see what people had already done, and I came across your project.

I don't know what your ultimate goals are? Do you intend to build something upon it that you get through the HMRC approval process?  Based on just the test suite, or more than that?

Anyway... I've begun work on some code to create CLI tools that are built on top of your library. My goal is to get something that is enough to be able to do all the interfacing with HMRC.

The project is here: https://github.com/DavidAnderson684/hmrc-php-cli . Currently there's just `create-test-user.php`, which creates a test user. I've run out of time for more work today. How complete is the rest of your SDK - if I develop against it, am I running ahead of where you are?

If you're interested in co-operating in some way to help each other I'd be very eager. Please let me know more of what your plans and thoughts are!

David

**Comment by EcoJames** [comment]
Hi David

Thanks for getting in touch, I'm sorry I didn't see this earlier. I have written this to use within our commercial software, https://ecooffice.eu, which has already passed the HMRC approval process

I've just added support for the Fraud Prevention headers, and will continue to maintain as necessary, however I don't really have the time to get involved in anything else. 

Ultimately the goal for HMRC seems to be to require all businesses to keep full digital records, so I think that command line tools for just submitting VAT returns would probably have a limited life span. However, right now there would probably be a market for it, so long as you keep it totally simple for the user

Kind regards

James

**Comment by DavidAnderson684** [comment]
Hi James,

Thank you. "Limited life span" - yes; in fact, in the meantime, I decided I had the wrong approach to my particular problem! I think the CLI tool still has some value for making testing of your library easier. But other than that, I don't plan to take it further.

David
